# Generated by Django 3.2.5 on 2021-08-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('platform', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='portfolio/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='portfolio/images/')),
                ('date', models.DateField()),
            ],
        ),
    ]
