# Generated by Django 3.2.5 on 2021-08-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210828_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finished',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
