# Generated by Django 3.2.5 on 2021-08-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210828_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Future',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='portfolio/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Upcoming',
        ),
        migrations.RemoveField(
            model_name='finished',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='sample',
            field=models.FileField(blank=True, upload_to='portfolio/uploads/'),
        ),
        migrations.AlterField(
            model_name='finished',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
