# Generated by Django 3.2.5 on 2021-08-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_future_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='future',
            name='release',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
