# Generated by Django 3.2.5 on 2021-09-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_future_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Audio_Work', models.CharField(choices=[('Song', 'Song'), ('Audiobook', 'Audiobook'), ('Animation', 'Animation'), ('Commercials', 'Commercials'), ('Announcing', 'Announcing')], default='Animation', max_length=20)),
            ],
        ),
    ]
