# Generated by Django 3.2.5 on 2021-09-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='sample',
            field=models.FileField(blank=True, upload_to='portfolio/uploads/'),
        ),
    ]
