# Generated by Django 3.2.5 on 2021-09-04 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_demo_sample'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demo',
            new_name='Recording',
        ),
    ]
